// calling in express to use its methods and functionality
const express = require('express');

// call in our functions from the controller
const { getBooks, getBook, createBook, updateBook, deleteBook } = require('../controllers/bookController.js');

// set up our router instance
const router = express.Router();

// define our routes/endpoints
// to get all books, we don't need to pass through the specific id of that book
router.get('/', getBooks);
// to get a specific book, we pass through that books ID
router.get('/:id', getBook);
// when creating a book, we don't need to pass through a specific ID either, as it is autogenerated
router.post('/', createBook);
// when updating a book, we want to update a SPECIFIC one, so we specify the ID
router.put('/:id', updateBook);
// when deleting we also pass an ID
router.delete('/:id', deleteBook);

// finally we export our routes
module.exports = router;